fix scoping for imagePullSecrets
zammad/zammad-helm pull request #117
Opened 2021-11-05 08:50 UTC by ifrido

#### What this PR does / why we need it:
Scoping for .Values.image.imagePullSecrets led to a templating error when providing secrets from values.

#### Which issue this PR fixes
--

#### Special notes for your reviewer:
--

#### Checklist
- [ ] Chart Version bumped

2021-11-21 11:36 UTC, zoomoid commented
This one's on me... sorry for any inconvenience this might have caused

2021-11-21 11:47 UTC, fibis commented
Can this please merged? We are getting the same error message when deploying zammad.

2021-12-03 23:53 UTC, zoomoid approved these changes
LGTM

2022-02-01 16:56 UTC, monotek requested changes
please raise chart version

2022-02-21 10:12 UTC, ifrido commented
> please raise chart version

my bad, did not read the manual closely.
version bumped to 6.0.5

2022-02-21 10:55 UTC, monotek requested changes

2022-02-21 10:55 UTC, monotek commented on zammad/Chart.yaml
> +    version: 6.0.2
As this is a major version upgrade only raising the bugfix chart version seems a bit risky.
The braking changes of the memcached chart should be mentioned in the upgrading section of this chart too.

2022-04-27 07:19 UTC, merged