Add support for sidecar container in statefulset
zammad/zammad-helm pull request #131
Opened 2022-05-24 05:53 UTC by aslubsky

#### What this PR does / why we need it:
Add support for sidecar container in statefulset. Weneed to run additinal container in zammad pod for backup storage file into aws s3.

#### Checklist

- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2022-05-24 09:13 UTC, monotek requested changes

2022-05-24 09:13 UTC, monotek commented on zammad/Chart.yaml
> +version: 6.4.2
new feature should raise minor version.
```suggestion
version: 6.5.0
```

2022-05-25 08:38 UTC, monotek requested changes
can we please also add an disabled example to the values file?

2022-05-25 08:53 UTC, aslubsky commented
> can we please also add an disabled example to the values file?

done

2022-05-25 09:02 UTC, monotek requested changes
please move above: https://github.com/zammad/zammad-helm/blob/43c3d9132add487115e4ce185944d1969038d0a0/zammad/values.yaml#L306

2022-05-25 09:08 UTC, aslubsky commented
> please move above:
> 
> https://github.com/zammad/zammad-helm/blob/43c3d9132add487115e4ce185944d1969038d0a0/zammad/values.yaml#L306

done

2022-05-25 09:19 UTC, monotek approved these changes

2022-05-25 21:57 UTC, merged