Added Redis User
zammad/zammad-helm pull request #166
Opened 2023-01-05 02:42 UTC by EvanLiu0

#### What this PR does / why we need it
Adds a Redis User to the connection string
- .

#### Which issue this PR fixes
Fixes #165 
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Special notes for your reviewer

- .

#### Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [ ] Chart Version bumped
- [ ] Upgrading instructions are documented in the README.md

2023-01-09 17:05 UTC, monotek commented on zammad/values.yaml
> +    []
please keep old format, also for all other lines.

2023-01-13 10:50 UTC, monotek requested changes
please also raise minor chart version

2023-03-25 07:37 UTC, closed without merging

2025-05-26 11:47 UTC, AirP0WeR commented
Hi @monotek kindly ask to add this feature to helm chart.

2025-05-26 12:05 UTC, MrGeneration commented
This PR was closed due to inactivity.