openshift unprivileged and with arbitrary UIDs and GIDs
zammad/zammad-helm pull request #177
Opened 2023-03-21 13:09 UTC by klml

#### What this PR does / why we need it

Adds values for openshift as discussed in #160

#### Which issue this PR fixes

- fixes #160

#### Special notes for your reviewer

tested on our testcluster

```
$ oc get po
NAME                                READY   STATUS    RESTARTS   AGE
postgresql-75cfcbb447-vtntk         1/1     Running   0          28h
zammad-0                            4/4     Running   0          2m46s
zammad-elasticsearch-master-0       1/1     Running   0          2m46s
zammad-memcached-7fd99d488f-qxqxh   1/1     Running   0          2m46s
zammad-redis-master-0               1/1     Running   0          2m46s
$ curl -s http://zammad-zammad.apps.capx.example.de/ | grep title
  <title>Zammad Helpdesk</title>
  <div class="splash-title">Loading…</div>
```

#### Checklist

- [x] Chart Version bumped
- [x] Upgrading instructions are documented in the README.md

2023-03-21 14:09 UTC, monotek requested changes
Please raise chart and zammad image version too:

```
version: 8.2.2
appVersion: 5.4.0-10
```

2023-03-21 16:28 UTC, monotek approved these changes

2023-03-21 16:28 UTC, monotek commented
Thanks for the PR :)

2023-03-21 16:28 UTC, merged

2023-03-22 06:38 UTC, mgruner commented
🙏